name: Rust (autotools)

on:
  push: 
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  autotools_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust-channel: [1.40, 1.41, 1.42, 1.43, 1.44, 1.45, 1.46, 1.47, 1.48, 1.49, 1.50, 1.51, 1.52, stable, beta,nightly]

    steps:
      - uses: actions/checkout@v2
      - name: Install Rustup Toolchain
        run: |
          rustup toolchain add --profile minimal ${{ matrix.rust-channel }}
          rustup default ${{ matrix.rust-channel }}
          rustup update
      - name: Create Build Directory
        run: mkdir -pv build
      - name: Build
        working-directory: ${{ github.workspace }}/build
        run: |
          ../configure
          make
          make check